version: 2

updates:
  - directory: "/"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
